name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: ' AdoptOpenJDK'   # Aquí se especifica la distribución de Java.
          java-version: '17'  # La versión de Java que quieres usar, por ejemplo 11.

      - name: Build with Gradle
        run: ./gradlew build
